<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/18 16:04:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=template_symfony',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
