<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/18 13:19:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=template-symfony',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
